#!/bin/sh
set -e

chmod +x /usr/local/bin/docker-log-linker
mkdir -p /var/log/docker-log-linker
touch /var/log/docker-log-linker/docker-log-linker.log

systemctl daemon-reload

# systemctl enable docker-log-linker.service >/dev/null || true
# systemctl start docker-log-linker.service >/dev/null || true

exit 0
