#!/bin/sh
set -e

chmod +x /usr/local/bin/docker-log-linker

# Copy sample config if it does not exist
if [ ! -f /etc/docker-log-linker/docker-log-linker.conf ]; then
    mkdir -p /etc/docker-log-linker
    cp /usr/share/docker-log-linker/docker-log-linker.conf.example /etc/docker-log-linker/docker-log-linker.conf
fi

systemctl daemon-reload

# systemctl enable docker-log-linker.service >/dev/null || true
systemctl start docker-log-linker.service >/dev/null || true

exit 0
